### ISSUE TITLE
Input field isn't visible on Sketch 43.2, MacOS v10.13.4

### ISSUE THREAD

**Issue by dkoprowski** [tankxu/SVG-Insert#3]
Input field isn't visible on Sketch 43.2, MacOS v10.13.4 then after clicking `OK` I see and error

![image](https://user-images.githubusercontent.com/2902306/43635761-55a7f21a-9710-11e8-9fa8-bc046b5eab58.png)

**Comment by tankxu** [comment]
Sorry to hear that. Sketch 43.2 is too old and i don't know how to solve this problem. Please update your Sketch to enjoy this plugin and other modern design features.
