### ISSUE TITLE
Feature request: auto-paste what's in the clipboard

### ISSUE THREAD

**Issue by jayliu50** [tankxu/SVG-Insert#6]
Hi! Excellent plugin! Thank you so much for writing it.

I have just a feature request: it would be very cool if the dialog could "sense" whether there is valid SVG already in the clipboard, and if so, automatically populate the dialog with the clipboard contents. 

Thanks!!

**Comment by tankxu** [comment]
Nice idea, but let a plugin listening the system clipboard contents is a hard job.

I think i can add a "Paste from clipboard" function to improve the efficiency in work. Then you can set a shortcut for this function, or use Sketch Runner to run the command fast.

I will try to do it, thanks for your suggestion.
